# Generated by Django 2.1.5 on 2019-01-15 20:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'MAC Address',
                'verbose_name_plural': 'MAC Addresses',
                'ordering': ['people'],
            },
        ),
        migrations.CreateModel(
            name='OnlineLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_online', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Online Log',
                'verbose_name_plural': 'Online Logs',
                'ordering': ['-date', 'people'],
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='home/photos/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='onlinelog',
            name='people',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='home.People'),
        ),
        migrations.AddField(
            model_name='macaddress',
            name='people',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.People'),
        ),
    ]
